# Generated by Django 4.1.5 on 2023-01-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_interaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accordsVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('id_product', models.IntegerField()),
                ('id_category', models.IntegerField()),
                ('id_provider', models.IntegerField()),
                ('id_vente', models.IntegerField()),
            ],
        ),
    ]
